version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=penny
  server:
    build:
      context: ./server
    volumes:
      - ./server:/go/src/penny/server
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db

  frontend:
    build:
      context: ./client
    volumes:
      - ./client/src:/client/src
    ports:
      - "8080:8080"
